apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odsdataconverter-persistent-volume-claim
  namespace: default
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi