apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: ods-dataconverter-service
  namespace: default
spec:
  template:
    spec:
      container:
        image: docker.io/lucacelardo/odsdataconverter:1.0.0
# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
  # name: ods-dataconverter-service
  # namespace: default
  # labels:
    # app: ods-dataconverter-service
# spec:
  # replicas: 1
  # selector:
    # matchLabels:
      # app: ods-dataconverter-service
  # template:
    # metadata:
      # labels:
        # app: ods-dataconverter-service
    # spec:
      # containers:
      # - name: ods-dataconverter-service
        # imagePullPolicy: Never
        # image: ods-dataconverter-service:v1
        # ports:
        # - containerPort: 80
        # volumeMounts:
        # - name: nfs-volume
          # mountPath: /app/nfs
          ##subPath: my-api
      # volumes:
      # - name: nfs-volume
        # persistentVolumeClaim:
          # claimName: odsdataconverter-persistent-volume-claim
          
# ---

# apiVersion: serving.knative.dev/v1alpha1
# kind: Service
# metadata:
  # name: ods-dataconverter-service
  # namespace: default
# spec:
  # runLatest:
    # configuration:
      # revisionTemplate:
        # spec:
          # container:
            # image: docker.io/lucacelardo/odsdataconverter:1.0.0
            ##image: gcr.io/knative-releases/github.com/knative/eventing-contrib/cmd/event_display
            
# ---

# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
  # annotations:
    # deployment.kubernetes.io/revision: "1"
    # serving.knative.dev/creator: minikube-user
  # creationTimestamp: "2020-03-06T11:42:59Z"
  # generation: 2
  # labels:
    # app: ods-dataconverter-service-s2jmh
    # serving.knative.dev/configuration: ods-dataconverter-service
    # serving.knative.dev/configurationGeneration: "1"
    # serving.knative.dev/revision: ods-dataconverter-service-s2jmh
    # serving.knative.dev/revisionUID: 9f681613-5f9f-11ea-81c8-080027ef1c70
    # serving.knative.dev/service: ods-dataconverter-service
  # name: ods-dataconverter-service-s2jmh-deployment
  # namespace: default
  # ownerReferences:
  # - apiVersion: serving.knative.dev/v1alpha1
    # blockOwnerDeletion: true
    # controller: true
    # kind: Revision
    # name: ods-dataconverter-service-s2jmh
    # uid: 9f681613-5f9f-11ea-81c8-080027ef1c70
  # resourceVersion: "396004"
  # selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/ods-dataconverter-service-s2jmh-deployment
  # uid: a133b73b-5f9f-11ea-81c8-080027ef1c70
# spec:
  # progressDeadlineSeconds: 120
  # replicas: 0
  # revisionHistoryLimit: 10
  # selector:
    # matchLabels:
      # serving.knative.dev/revisionUID: 9f681613-5f9f-11ea-81c8-080027ef1c70
  # strategy:
    # rollingUpdate:
      # maxSurge: 25%
      # maxUnavailable: 25%
    # type: RollingUpdate
  # template:
    # metadata:
      # annotations:
        # serving.knative.dev/creator: minikube-user
        # sidecar.istio.io/inject: "true"
        # traffic.sidecar.istio.io/includeOutboundIPRanges: '*'
      # creationTimestamp: null
      # labels:
        # app: ods-dataconverter-service-s2jmh
        # serving.knative.dev/configuration: ods-dataconverter-service
        # serving.knative.dev/configurationGeneration: "1"
        # serving.knative.dev/revision: ods-dataconverter-service-s2jmh
        # serving.knative.dev/revisionUID: 9f681613-5f9f-11ea-81c8-080027ef1c70
        # serving.knative.dev/service: ods-dataconverter-service
    # spec:
      # containers:
      # - env:
        # - name: PORT
          # value: "8080"
        # - name: K_REVISION
          # value: ods-dataconverter-service-s2jmh
        # - name: K_CONFIGURATION
          # value: ods-dataconverter-service
        # - name: K_SERVICE
          # value: ods-dataconverter-service
        # image: index.docker.io/lucacelardo/odsdataconverter@sha256:39aeff19028afdf469a59f614402257ea7f153915ee2314ea1a1bdd225ae4740
        # imagePullPolicy: IfNotPresent
        # name: user-container
        # ports:
        # - containerPort: 8080
          # name: user-port
          # protocol: TCP
        # volumeMounts:
        # - mountPath: /var/log
          # name: knative-var-log
        # securityContext:
          # allowPrivilegeEscalation: false
      # - emptyDir: {}
        # name: knative-var-log
        
# ---

# apiVersion: serving.knative.dev/v1alpha1
# kind: Service
# metadata:
  # name: ods-dataconverter-service
  # namespace: default
# spec:
  # runLatest:
    # configuration:
      # revisionTemplate:
        # spec:
          # container:
              # image: docker.io/lucacelardo/odsdataconverter:1.0.0
              # volumeMounts:
                # - name: nfs-volume
                  # mountPath: /app/nfs
          # volumes:
            # - name: nfs-volume
              # nfs:
                # server: 10.108.211.244
                # path: /

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
  # name: ods-dataconverter-deployment
  # namespace: default
  # labels:
    # app: ods-dataconverter-service
# spec:
  # replicas: 1
  # selector:
    # matchLabels:
      # app: odsdataconverter-service
  # template:
    # metadata:
      # labels:
        # app: odsdataconverter-service
        # tier: CORE
    # spec:
      # volumes:
        # - name: nas
          # persistentVolumeClaim:
            # claimName: odsdataconverter-persistent-volume-claim
      # containers:
        # - name: user-container
          # image: docker.io/lucacelardo/odsdataconverter:1.0.0
          # securityContext:
            # privileged: true
          # command: ["/bin/sh"]
          # args: ["-c", "while true; do date >> /app/nfs/dates.txt; sleep 5; done"]
          # env:
            # - name: KUBERNETES_NAMESPACE
              # value: default
          # volumeMounts:
            # - name: nas # This is the name of the volume we set at the pod level
              # mountPath: /app/nfs # Where to mount this directory in our container
          # ports:
            # - containerPort: 8080
          # imagePullPolicy: Always
      # restartPolicy: Always
      
# ---      

# apiVersion: v1
# kind: Pod
# metadata:
  # name: ods-dataconverter-service
  # namespace: default
  # labels:
    # app: ods-dataconverter-service
# spec:
  # volumes:
    # - name: nas
      # persistentVolumeClaim:
        # claimName: odsdataconverter-persistent-volume-claim
  # containers:
    # - name: app
      # image: alpine
      # volumeMounts:
        # - name: nas
          # mountPath: /app/nfs
      ##command: ["/bin/sh"]
      ##args: ["-c", "while true; do date >> /var/nfs/dates.txt; sleep 5; done"]