apiVersion: v1
kind: PersistentVolume
metadata:
  name: odsdataconverter-persistent-volume
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.43.32
    path: /C/Users/Luca/IdeaProjects/UseCaseNEXI/nfs
  mountOptions:
    - nfsvers=3
    - udp