apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: ods-datamartextractor-service
  namespace: default
spec:
  template:
    spec:
      container:
        image: docker.io/lucacelardo/odsdatamartextractor:1.0.0