# --- kafka source ---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: ods-filemanager-kafka-source
spec:
  consumerGroup: ods-filearchiver-consumer-group-id
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  topics: filemanager-source-topic
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: ods-filearchiver-service